### ISSUE TITLE
Support command line in executablePath

### ISSUE THREAD

**Issue by felipecrs** [timonwong/vscode-shellcheck#115]
If executablePath could support a command line, the users could easily use WSL with something like `wsl shellcheck` or even the Docker version, with `docker run [...] shellcheck`.

So we would not need to maintain custom logic such as the `useWsl` one.

References https://github.com/timonwong/vscode-shellcheck/issues/87.

**Comment by beltaurus** [comment]
Why not just use WSL remote? It has been designed to use your full WSL environment on your Windows data, through the Windows GUI?

If that is not acceptable, then you can just create a custom command, and wrap it around a wsl command.
This custom command can then be used in the VS Code settings...

**Comment by felipecrs** [comment]
> Why not just use WSL remote?

Absolutely. That's what I do. But it seems that some users still want to use `shellcheck` installed on WSL to lint scripts on Windows.

> then you can just create a custom command, and wrap it around a wsl command

Yes, but we currently support the feature `useWsl`, the goal of this proposal is to give users more seamless approach.

In any case, I don't believe everything in this sense is all that needed nowadays, since all the binaries that the extension need is shipped with it itself, in every platform. That's why I proposed to deprecate `useWsl`, since it seems to be causing some issues with other users.

**Comment by beltaurus** [comment]
Henry Ford said that if we always listen to the customers, instead of cars we would have bigger stronger horses now....

If the user WANTS to use the WSL shellcheck while using the native VS Code, well, they can do that (with a .bat wrapper).
But I would hate to build this into the VS Code setup. The mark of a great GUI is "KISS" (keep it simple, stupid!)... All those bells and whistles to accommodate the outliers make the core of the user rather unhappy.

I am already upset when I need to change a setting in the GUI: so many settings, all for corner cases that just don't make sense for the rational user... I have to scroll back and forward between completely redundant and moot settings before I find the essential ones...

An example is 3rd party tool initialization. Such tools already HAVE an initialization file/mechanism (e.g. `.rc` files on Unix, and `.init` files on Windows). I never see a good reason to try to duplicate that functionality in the VS Code extension setup... You can do it already, and it is a one-time effort! Don't make the VS Code GUI more complicated and elaborate for something that you can already do...

I'll get off my soap box now...

I think we are in violent agreement to remove `useWsl`. My assumption is that it does exactly what a DOS wrapper would do to access shellcheck in WSL?
So for the people who want this, for some obscure reason: no need to have a feature in shellcheck-vscode... They can create a wrapper, and leave the rest of us in peace :-)

**Comment by felipecrs** [comment]
@beltaurus I really enjoyed reading your comment.

I totally agree with you regarding multiple configuration sources by the way, nonetheless, `.shellcheckrc` in our case does not accept all the possible configurations, just the ones which are writable in the scripts itself. That's why the extension provides the "options".

> I think we are in violent agreement to remove useWsl. My assumption is that it does exactly what a DOS wrapper would do to access shellcheck in WSL?
So for the people who want this, for some obscure reason: no need to have a feature in shellcheck-vscode... They can create a wrapper, and leave the rest of us in peace :-)

Yeah... You think you're right. But if the implementation of what I explained in the Issue is simple, why not? It would be harmless at least.

**Comment by timonwong** [comment]
Yeah the WSL support is always a headache, we certainly do not know how to resolve bugs & make improvements about it (and it's getting worse since here comes WSL2...) 😂 

A batch wrapper may a good alternative (though we still execute it with cmd.exe /c xxxx.bat, which is not elegant)

For remote ones, maybe we should implement the language server protocol?

**Comment by felipecrs** [comment]
> For remote ones, maybe we should implement the language server protocol?

Forgive me, but what are the advantages? I think I'm not up-to-date.

**Comment by beltaurus** [comment]
Can you leverage the existing Bash Language Server?

**Comment by felipecrs** [comment]
Let's move the discussion about the language server protocol to the right issue: https://github.com/timonwong/vscode-shellcheck/issues/114

**Comment by felipecrs** [comment]
I'm going to close this for now, as probably the use cases don't seem to worth it.
