### ISSUE TITLE
Using -x only follows correct file relative to project root

### ISSUE THREAD

**Issue by fetmar** [timonwong/vscode-shellcheck#19]
Let's say my structure is this:

```
.
+-- top.sh
+-- subdir
|   +-- some-script.sh
|   +-- common.sh
```

Now if `top.sh` has a line that says `source ./subdir/common.sh`, then -x works without an error. If `some-script.sh` has a line that says `source ./common.sh` the following doesn't work, it gives the following error:

```
{
	"resource": "[REDACTED]",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "1091",
	"severity": 2,
	"message": "Not following: ./common.sh: openBinaryFile: does not exist (No such file or directory) [SC1091]",
	"source": "shellcheck",
	"startLineNumber": 4,
	"startColumn": 1,
	"endLineNumber": 4,
	"endColumn": 1
}
```

If I change the line in **some-script.sh** to `source ./subdir/common.sh`, then it works without the error.

**Comment by timonwong** [comment]
Hi, `v0.5.1` just released which should fix this problem.

**Comment by DamianRivas** [comment]
Hi @timonwong 

This "problem" that you fixed is actually how I need it to behave and it works fine with `shellcheck` but not with this extension.

Using fetmar's same scenario, suppose I do want to have `source ./subdir/common.sh` in **some-script.sh** because I am running shellcheck strictly from the project's root directory.

Running `shellcheck -x ./subdir/some-script.sh` works perfectly, but the extension keeps complaining with SC1091.

Overall, the extension has been immensely helpful except for this issue that's popping up all over my test scripts.

**Comment by DamianRivas** [comment]
Also, there is currently a debate on the main shellcheck repo on how this should work: https://github.com/koalaman/shellcheck/issues/769

I think this is something that can be fixed easily in the extension but not in the main repo. If you can make it so that we have a choice on how `shellcheck` is run (e.g., from the project's root, or relative to the file's directory) it should satisfy most use cases.

**Comment by jcrben** [comment]
Has there been progress on this? Trying to deal with something like this:
![image](https://user-images.githubusercontent.com/5614134/72197279-63e11480-33d4-11ea-86e7-63f1cacc8737.png)

Setting `# shellcheck source=/dev/null` in the meantime fixes it...
