### ISSUE TITLE
Improve README / documentation

### ISSUE THREAD

**Issue by hohwille** [timonwong/vscode-shellcheck#50]
Sorry for being a lame DAU but I followed your instructions to install shellcheck and your plugin into vscode. I also read about configuration options. But now? How to make actually use of your plugin? I open a bash script and nothing happens, no options for shellcheck in context menu and no warnings, just nothing.
Some screenshot how to use your plugin (at least if it actually does something) would be great.

**Comment by saxonww** [comment]
I ran into the same issue after having installed both `shellcheck` and `code` via Ubuntu snap packages. Something about the snap confinement design prevents this extension from working in that configuration. Removing the `code` snap and installing as a regular system package fixed the issue.

It seems very similar/identical to [this issue](https://forum.snapcraft.io/t/go-snap-vscode-snap-go-extension-breaks-error-checking/7458) detailed in the snapcraft forums, for anyone else experiencing this. The explanation about the confinement context being the culprit is [here](https://forum.snapcraft.io/t/snapd-2-32-breaks-live-server-installer/4597/9).

**Comment by ahmgithubahm** [comment]
@hohwille I agree.  Did you actually find how to invoke this extension on a shell script ?

**Comment by djnorrisdev** [comment]
I have the same issue. The only bash extension I have on vscode is this one, and I can't get it to work at all.

**Comment by CaptchaTW** [comment]
Confusing point about the documentation. It mentions to "Ensure shellcheck is installed (v0.7.0 or better is recommended to use)." but this overlaps with the extension name. Adding some kind of nomenclature to differ spellcheck executable versus spellcheck extension would be helpful.

**Comment by felipecrs** [comment]
I'll add to the documentation:

![vscode-1612448787358](https://user-images.githubusercontent.com/29582865/106907134-c299c000-66b2-11eb-8d8b-ea1bd898cb3a.gif)
