### ISSUE TITLE
Feature Request: Optionally install the new official precompiled binaries for macOS and Linux aarch64 from shellcheck >0.7.0 

### ISSUE THREAD

**Issue by David-Else** [timonwong/vscode-shellcheck#71]
https://github.com/koalaman/shellcheck/blob/master/CHANGELOG.md
```
v0.7.0 - 2019-07-28
Added

    Precompiled binaries for macOS and Linux aarch64
```
Could be pretty cool :) Would be good to make it a clear option though as some Linux users will only want to use their distro's binaries. Maybe it detects if you have shellcheck in the path and says something like:

"shellcheck version xxx detected on your machine, would you like to use the bundled version xxx instead?"
"you don't have any version of shellcheck installed, would you like to use the bundled version xxx?"
"you are using windows. this is 2019, are you insane? please install linux" :)

Thanks for this fantastic extension!

**Comment by felipecassiors** [comment]
There is another, easier to implement and user-friendlier: 

https://www.npmjs.com/package/shellcheck

**Comment by electrovir** [comment]
apt-get was giving me an old version apparently... so I just went with the npm package as well and now everything is great.

**Comment by felipecassiors** [comment]
Actually, https://www.npmjs.com/package/shellcheck won't work so well, since it doesn't work for Windows.

@timonwong, I'm willing to help. Seems like there are people who support bundling the binaries required for the extensions in the extension package itself. 

[Official Java VS Code extension](https://github.com/redhat-developer/vscode-java) and [bash-debug](https://github.com/rogalmic/vscode-bash-debug) is some of them. Java extension has more than 50MB of size due to this, but if we bundle shellcheck binaries with this extension it would a lot lesser.

This should be considered as a workaround until we have the solution for https://github.com/microsoft/vscode/issues/23251.

**Comment by prashantvc** [comment]
👋 I am Program manager on VS Marketplace team. We are working on solving this issue(https://github.com/microsoft/vscode/issues/23251) of distributing dependencies from the Marketplace. I would love to get your opinion (30mins call), it will help us to build a better solution

Please use the link to pick time that works for you https://aka.ms/vsm-call
