### ISSUE TITLE
WLS Cannot shellcheck the shell script. The shellcheck program was not found. Use the 'shellcheck.executablePath' setting to configure the location of 'shellcheck'

### ISSUE THREAD

**Issue by snevs** [timonwong/vscode-shellcheck#9]
I keep getting this error:

Cannot shellcheck the shell script. The shellcheck program was not found. Use the 'shellcheck.executablePath' setting to configure the location of 'shellcheck'

even though the path is set correctly: 

    "shellcheck.executablePath": "C:\\windows\\sysnative\\bash.exe -c shellcheck %*"

**Comment by chrisjohntapp** [comment]
I'm having this on Linux too. vscode fails to autodetect the executable even though it's in a standard place, then I still get the error message even when explicitly adding the correct path:

    "shellcheck.executablePath": "/usr/bin/shellcheck"

**Comment by chrisjohntapp** [comment]
I removed the flatpak version and installed the .deb (same version) and the issue is gone.

**Comment by rogalmic** [comment]
On windows, this works for me:
```
    "shellcheck.enable": true,
    "shellcheck.run": "onType",
    "shellcheck.exclude": [],
    "shellcheck.useWSL": true
```

WSL = Windows Subsystem Linux

**Comment by Pitterling** [comment]
Some here for Windows. It was working before, but now with recent VSCode Update it stopped.
I used procmon and can see, that VSCode is actually finding the executable !!!

![image](https://user-images.githubusercontent.com/4181164/45213137-ff212180-b296-11e8-9a2c-e60abab3fb16.png)

what else could cause this error message?

**Comment by beltaurus** [comment]
I think the problem might be with the fact that settings should be different for
- the "LOCAL" User extension (Install) 
- versus the "Remote[WSL] extension ("Install in WSL").

I have shellcheck (the application) installed:

- On my Windows 10 machine, through chocolatey (https://chocolatey.org/packages/shellcheck): version 0.6.0...
- On my WSL Ubuntu18.04LTS distro, through the .deb file (https://packages.debian.org/sid/amd64/shellcheck/download): version 0.5.0...
- I don't want to install from the Ubuntu repository, because that version is rather old (0.4.6).

This allows for the following configurations...

### User Settings, local shellcheck
```
ExecutablePath: "C:\ProgramData\chocolatey\bin\shellcheck.exe"
[ ] Use WSL
```

Indeed, with those settings I can confirm that I'm using the local application, not the WSL version.

### User Settings, remote shellcheck
```
ExecutablePath: "/usr/local/bin/shellcheck"
[v] Use WSL
```

Indeed, with those settings I can confirm that I'm using the application installed in WSL.

_Note that the "ExecutablePath" can be just "shellcheck", if the application is in the **%Path%** for windows, and in the **$PATH** for WSL._

### Remote [WSL] Settings
Here is where the power of WSL comes in, I can choose:
`ExecutablePath: "/mnt/c/ProgramData/chocolatey/bin/shellcheck.exe"`
(runs the Windows application)

`ExecutablePath: "/usr/local/bin/shellcheck"` 
(runs the WSL application)

However, the "Use WSL" check box doesn't make any sense... Relative to WSL, there is no "WSL", so as soon as you select this option, you'll get the confusing:
![image](https://user-images.githubusercontent.com/54114043/64562490-f461f800-d301-11e9-8fe4-b4a41614a9a6.png)

If it is possible to remove this setting for "Remote [WSL]" that would eliminate any potential confusion...

**Comment by beltaurus** [comment]
Slightly related to this: Just like it is straightforward to run a Windows Application in the WSL environment, it should be equally straightforward to run a WSL Application in the User environment.

To that intent, I had tried:
`ExecutablePath: wsl /usr/local/bin/shellcheck
`
That works just fine from a CMD line, but to my surprise it doesn't work as a shellcheck User Setting...

If we can get this to work, I believe the use model is a lot more trivial, and we can get rid of the "Use WSL" check box altogether...

**Comment by GongT** [comment]
Not work when connected to any remote. (I'm using ssh)

**Comment by rpf3** [comment]
@beltaurus fix worked for me, it was the "Use WSL" setting that was causing the issues.

**Comment by mahmoudshirivaramini** [comment]
I got the same error on macOS Catalina(version 10.15.3), VSCode(Version: 1.44.0), shellcheck(0.9.0). I solved the problem using the [brew](https://github.com/Homebrew/brew)  to install spellcheck binary:
```shell
brew install shellcheck
```
and after installation, everything was going to be all right.

**Comment by skupjoe** [comment]
I'm having this same error on Windows recently, with shellcheck installed via scoop/choco (I tried both). The extension used to work fine, I don't know what changed.

The shellcheck command works at a command prompt, but the VScode extension gives me this error. I also tried setting `"shellcheck.executablePath` manually with the local/absolute path.

**Comment by felipecrs** [comment]
It's working here for me using the binaries provided by the extension (just leave the executablePath blank) as below:

![image](https://user-images.githubusercontent.com/29582865/117661029-38ab3880-b174-11eb-8685-7ebc573b1c7a.png)

**Comment by atreyd** [comment]
I am using v0.14.04 with WSL and getting this error `The shellcheck program was not found (not installed?). Use the 'shellcheck.executablePath' setting to configure the location of 'shellcheck'`. Although, the `shellcheck` command works from WSL.
I have tried adding the path `/usr/bin/shellcheck` to the 'shellcheck.executablePath' but no luck.

**Comment by felipecrs** [comment]
Are you sure the extension is installed in WSL and not in Windows? Also, you can try to write just `shellcheck` in the `executablePath`.

**Comment by atreyd** [comment]
> Are you sure the extension is installed in WSL and not in Windows? Also, you can try to write just `shellcheck` in the `executablePath`.

Yes, I installed the shellcheck with `apt install shellcheck` on my WSL. I tried with just `shellcheck` in the `executablePath` but it didn't work. The surprising part is, it was working till yesterday.

After adding the `executablePath` to the extension settings in vs-code it gives a warning. (see the screenshot
![shellcheck](https://user-images.githubusercontent.com/25500634/125084143-d1afee80-e0e6-11eb-9a97-35175aec430c.png)
)

**Comment by felipecrs** [comment]
I meant if the vscode extension is installed in WSL. 

![image](https://user-images.githubusercontent.com/29582865/125084623-1ebca200-e0a0-11eb-8997-cf2572829fe8.png)

If it is like my screenshot above, this means you installed the extension on Windows, not on WSL. Simply click the green button to install.

**Comment by felipecrs** [comment]
Also, you may not be configuring shellcheck for WSL, but for Windows, make sure you are in the Remote tab in the settings:

![image](https://user-images.githubusercontent.com/29582865/125086299-e027e700-e0a1-11eb-9141-45dc495330af.png)

**Comment by atreyd** [comment]
I have the same settings but it was not working. However the twist is, I had to reboot my laptop and when I restarted it, it started working.

**Comment by taiyodayo** [comment]
I had the same error pop up on my M1 MacBook / Big Sur.
after ```brew install shellcheck```,  adjust settings entry "Executable Path" to the result of ```which shellcheck```
which in my case is ```/opt/homebrew/bin/shellcheck``` and all is well. 

maybe the extension looks for old homebrew install path by default?

**Comment by felipecrs** [comment]
The extension searches for "shellcheck" in your PATH. It was supposed to find, I guess.

**Comment by felipecrs** [comment]
Yes, maybe... tell us if the error happens again. I know this is very annoying, and the extension is supposed to look for shellcheck in your PATH.
